api:
  title: "YuQing舆情分析系统"
  version: "2.0.0"
  
data_sources:
  cailian:
    enabled: true
    update_interval: 300  # 5分钟
    
  google_news:
    enabled: true
    rss_urls:
      - "https://news.google.com/rss"
      
ai_analysis:
  deepseek:
    concurrent_requests: 10
    timeout: 30

